import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

import { eligible, mergeConflict, newerSha, resolveTree } from '../resolve-sync-conflicts.mjs';

const OLD = 'a'.repeat(40);
const BASE = 'b'.repeat(40);
const HEAD = 'c'.repeat(40);
const REPO = 'workos/openapi-spec';
const pr = {
  state: 'open', draft: false,
  user: { login: 'workos-sdk-automation[bot]' },
  base: { ref: 'main', repo: { full_name: REPO } },
  head: { ref: 'update-spec-123', repo: { full_name: REPO } },
  labels: [{ name: 'autogenerated' }],
};

function git(cwd, ...args) {
  return execFileSync('git', args, { cwd, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }).trim();
}

function fixture(t, codeConflict = false) {
  const root = mkdtempSync(join(tmpdir(), 'sync-conflict-test-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const cwd = join(root, 'repo');
  mkdirSync(cwd);
  git(cwd, 'init', '-b', 'main');
  // Fixture commits are signed too; no user key or agent prompt is needed.
  execFileSync('ssh-keygen', ['-q', '-t', 'ed25519', '-N', '', '-f', join(root, 'key')]);
  for (const [key, value] of Object.entries({
    'user.name': 'Test', 'user.email': 'test@example.com',
    'commit.gpgsign': 'true', 'gpg.format': 'ssh',
    'gpg.ssh.program': 'ssh-keygen', 'user.signingkey': join(root, 'key'),
  })) git(cwd, 'config', key, value);
  const spec = `first: old\n${'\n'.repeat(10)}last: old\n`;
  writeFileSync(join(cwd, '.last-synced-sha'), `${OLD}\n`);
  writeFileSync(join(cwd, 'spec.yaml'), spec);
  git(cwd, 'add', '.');
  git(cwd, 'commit', '-m', 'test: seed');
  const ancestor = git(cwd, 'rev-parse', 'HEAD');
  git(cwd, 'checkout', '-b', 'update-spec-123');
  writeFileSync(join(cwd, '.last-synced-sha'), `${HEAD}\n`);
  writeFileSync(join(cwd, 'spec.yaml'), spec.replace('first: old', 'first: head'));
  git(cwd, 'commit', '-am', 'test: head');
  const head = git(cwd, 'rev-parse', 'HEAD');
  git(cwd, 'checkout', 'main');
  writeFileSync(join(cwd, '.last-synced-sha'), `${BASE}\n`);
  writeFileSync(join(cwd, 'spec.yaml'), codeConflict
    ? spec.replace('first: old', 'first: base')
    : spec.replace('last: old', 'last: base'));
  git(cwd, 'commit', '-am', 'test: base');
  return { root, cwd, ancestor, head, base: git(cwd, 'rev-parse', 'HEAD') };
}

test('only same-repository, labeled, open sync-bot PRs are eligible', () => {
  assert.equal(eligible(pr), true);
  for (const override of [
    { state: 'closed' }, { draft: true }, { labels: [] },
    { user: { login: 'someone-else' } },
    { head: { ...pr.head, repo: { full_name: 'someone/fork' } } },
    { head: { ...pr.head, ref: 'feature' } },
    { base: { ...pr.base, ref: 'release' } },
  ]) assert.equal(eligible({ ...pr, ...override }), false);
});

test('source ancestry, not SHA ordering, picks the newest value; unknown ancestry fails closed', () => {
  assert.equal(newerSha(BASE, HEAD, 'ahead'), HEAD);
  assert.equal(newerSha(BASE, HEAD, 'behind'), BASE);
  assert.equal(newerSha(BASE, BASE, 'identical'), BASE);
  for (const status of ['diverged', 'identical', undefined]) {
    assert.throws(() => newerSha(BASE, HEAD, status), /Cannot order/);
  }
  assert.throws(() => newerSha('main', HEAD, 'ahead'), /Invalid source SHA/);
});

test('SHA-only resolution preserves both sides of the code merge without touching the checkout', (t) => {
  const { cwd, head, base } = fixture(t);
  const conflict = mergeConflict(cwd, head, base);
  assert.equal(conflict.baseSource, BASE);
  assert.equal(conflict.headSource, HEAD);
  assert.match(git(cwd, 'show', `${conflict.tree}:.last-synced-sha`), /<<<<<<</);
  for (const [source, commit] of [[HEAD, head], [BASE, base]]) {
    const tree = resolveTree(cwd, conflict.tree, commit);
    assert.equal(git(cwd, 'show', `${tree}:.last-synced-sha`), source);
    const mergedSpec = git(cwd, 'show', `${tree}:spec.yaml`);
    assert.match(mergedSpec, /first: head/);
    assert.match(mergedSpec, /last: base/);
    assert.doesNotMatch(mergedSpec, /<<<<<<</);
  }
  assert.equal(git(cwd, 'status', '--porcelain'), '');
  assert.equal(git(cwd, 'rev-parse', 'HEAD'), base);
});

test('real code conflicts and clean merges are left alone', (t) => {
  const { cwd, ancestor, head, base } = fixture(t, true);
  assert.equal(mergeConflict(cwd, head, base), null);
  assert.equal(mergeConflict(cwd, head, ancestor), null);
  assert.equal(git(cwd, 'status', '--porcelain'), '');
});

test('invalid marker contents are rejected before querying upstream', (t) => {
  const { cwd, head } = fixture(t);
  writeFileSync(join(cwd, '.last-synced-sha'), 'not-a-sha\n');
  git(cwd, 'commit', '-am', 'test: invalid marker');
  assert.throws(() => mergeConflict(cwd, head, git(cwd, 'rev-parse', 'HEAD')), /Invalid source SHA/);
});

function mockGitHub(root) {
  const bin = join(root, 'bin');
  mkdirSync(bin);
  writeFileSync(join(bin, 'gh'), `#!/usr/bin/env node
const fs = require('node:fs');
const args = process.argv.slice(2);
const endpoint = args.find(arg => arg.startsWith('repos/'));
const data = args.includes('--input') ? JSON.parse(fs.readFileSync(0, 'utf8')) : undefined;
const previous = fs.readFileSync(process.env.API_LOG, 'utf8');
fs.appendFileSync(process.env.API_LOG, JSON.stringify({ endpoint, data }) + '\\n');
let result;
if (endpoint.endsWith('/pulls/184')) {
  result = JSON.parse(process.env.PR);
  if (process.env.RACE && previous.includes('/git/commits')) result.head.sha = 'd'.repeat(40);
} else if (endpoint.endsWith('/git/ref/heads/main')) result = { object: { sha: process.env.BASE } };
else if (endpoint.includes('/compare/')) result = { status: 'ahead' };
else if (endpoint.endsWith('/git/blobs')) result = {};
else if (endpoint.endsWith('/git/trees')) result = { sha: process.env.TREE };
else if (endpoint.endsWith('/git/commits')) result = { sha: 'e'.repeat(40), verification: { verified: !process.env.UNSIGNED } };
else if (endpoint.includes('/git/refs/heads/')) result = {};
else throw new Error('Unexpected API call: ' + endpoint);
console.log(JSON.stringify(result));
`, { mode: 0o755 });
  return bin;
}

test('CLI dry-run and signed, non-forced publication use live main, not stale PR base metadata', (t) => {
  const { root, cwd, head, ancestor } = fixture(t);
  // The real spec exceeds execFileSync's default 1 MiB buffer; preserve bytes too.
  writeFileSync(join(cwd, 'large.bin'), Buffer.alloc(1024 * 1024 + 1, 255));
  git(cwd, 'add', '.');
  git(cwd, 'commit', '-m', 'test: large binary on main');
  const base = git(cwd, 'rev-parse', 'HEAD');
  git(cwd, 'remote', 'add', 'origin', cwd);
  const tree = resolveTree(cwd, mergeConflict(cwd, head, base).tree, head);
  const bin = mockGitHub(root);
  const log = join(root, 'api.jsonl');
  const env = {
    ...process.env, PATH: `${bin}:${process.env.PATH}`, API_LOG: log, TREE: tree, BASE: base,
    PR: JSON.stringify({ ...pr, number: 184, head: { ...pr.head, sha: head }, base: { ...pr.base, sha: ancestor } }),
  };
  const script = fileURLToPath(new URL('../resolve-sync-conflicts.mjs', import.meta.url));
  for (const scenario of ['dry-run', 'write', 'unsigned', 'race']) {
    writeFileSync(log, '');
    const result = spawnSync(process.execPath, [script, '--pr', '184', ...(scenario === 'dry-run' ? [] : ['--write'])], {
      cwd, encoding: 'utf8', env: { ...env, UNSIGNED: scenario === 'unsigned' ? '1' : '', RACE: scenario === 'race' ? '1' : '' },
    });
    assert.equal(result.status, ['unsigned', 'race'].includes(scenario) ? 1 : 0, result.stderr);
    const calls = readFileSync(log, 'utf8').trim().split('\n').map(JSON.parse);
    if (scenario === 'dry-run') {
      assert.match(result.stdout, /Would resolve/);
      assert.equal(calls.filter(call => call.data).length, 0);
      continue;
    }
    const blobs = calls.filter(call => call.endpoint.endsWith('/git/blobs'));
    assert.ok(blobs.some(call => Buffer.from(call.data.content, 'base64').equals(Buffer.alloc(1024 * 1024 + 1, 255))));
    const commit = calls.find(call => call.endpoint.endsWith('/git/commits')).data;
    assert.deepEqual(commit.parents, [head, base]);
    assert.equal(commit.tree, tree);
    assert.equal(commit.author, undefined);
    const uploaded = calls.find(call => call.endpoint.endsWith('/git/trees')).data.tree;
    assert.equal(uploaded.find(entry => entry.path === 'spec.yaml').sha, git(cwd, 'rev-parse', `${tree}:spec.yaml`));
    const updates = calls.filter(call => call.endpoint.includes('/git/refs/heads/'));
    assert.equal(updates.length, scenario === 'write' ? 1 : 0);
    if (scenario === 'write') assert.deepEqual(updates[0].data, { sha: 'e'.repeat(40), force: false });
    if (scenario === 'unsigned') assert.match(result.stderr, /unsigned merge commit/);
    if (scenario === 'race') assert.match(result.stderr, /changed during resolution/);
  }
  assert.equal(git(cwd, 'status', '--porcelain'), '');
});
